### ISSUE TITLE
drone build is failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud-ci/php#118]
It was failing recently on the public drone. It has been just moved to https://drone.owncloud.com/owncloud-ci/php/438/1/2 but that is also failing.

Need to investigate.

**Comment by phil-davis** [comment]
@micbar there is lots of log output in the drone CI failures of https://drone.owncloud.com/owncloud-ci/php/438/1/2

**Comment by phil-davis** [comment]
The same is still happening. I tried restarting just now: https://drone.owncloud.com/owncloud-ci/php/440/1/2
```
latest: Pulling from plugins/docker
Digest: sha256:60f36379eb3f1b27a61f7c0a275dd260387a00af1144345976475b2a35e5ee4f
Status: Downloaded newer image for plugins/docker:latest
+ /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock
Detected registry credentials
+ /usr/local/bin/docker version
Client: Docker Engine - Community
 Version:           19.03.8
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false
time="2020-12-17T03:38:44Z" level=fatal msg="exit status 1"
```

@micbar @xoxys any ideas?

**Comment by xoxys** [comment]
Even if CI is green again labels should be cleaned up... looks like latest is no longer latest

**Comment by phil-davis** [comment]
From discussion: nobody is/should use `latest`

IMO `latest` is intended to be the latest PHP version that ownCloud 10 will actually run on, which would currently be PHP 7.4
