### ISSUE TITLE
Drop PHP 5.6

### ISSUE THREAD

**Issue by phil-davis** [owncloud-ci/php#123]
Blocked by https://github.com/owncloud/client-updater-server/issues/97

And what else still uses PHP 5.6 in CI?

**Comment by phil-davis** [comment]
Note FYI: https://github.com/owncloud/update-testing/blob/master/.drone.yml manages to do installs and upgrades from old oC10 versions using PHP 7. It does not need PHP 5.6.

**Comment by xoxys** [comment]
@phil-davis so we can finally remove it here, right?

**Comment by phil-davis** [comment]
> @phil-davis so we can finally remove it here, right?

yes, I don 't see any need for it any more. We can remove from CI. If the current latest docker image stays online, I don't see a problem with that. If it disappears completely, that is also OK.
