### ISSUE TITLE
Cleanup latest

### ISSUE THREAD

**Issue by phil-davis** [owncloud-ci/php#124]
- decide if `latest` is useful

https://github.com/owncloud-ci/php/issues/118#issuecomment-747442021

https://github.com/owncloud-ci/php/issues/118#issuecomment-747483808

Probably we can just get rid of it.

Do docker images have to have a `latest` ?

**Comment by xoxys** [comment]
> Do docker images have to have a latest ?

No, but maybe we can just implement a way to tag a given version e.g. 8.0 as latest too

**Comment by xoxys** [comment]
Sorry, wrong button :)

**Comment by DeepDiver1975** [comment]
especially in the ci usage I see no need in latest tag - we always want to explicitly pick an explicit version of php.

**Comment by xoxys** [comment]
`latest` tag doesn't exist on the registry anymore, closing.
