### ISSUE TITLE
Monthly or quarterly rebuild

### ISSUE THREAD

**Issue by phil-davis** [owncloud-ci/php#125]
This morning I restarted the drone merge CI: https://drone.owncloud.com/owncloud-ci/php/466

It passed, which is a good thing.

I restarted it because new patch releases of PHP 8.0.1 and 7.4.x were released on 2021-01-07. The re-run of the merge CI docker publishes new releases of the docker images https://registry.hub.docker.com/r/owncloudci/php/tags?page=1&ordering=last_updated - those should now have PHP 8.0.1, but I just pulled `docker pull owncloudci/php:8.0` and it seems to only have 
```
# php --version
PHP 8.0.0 (cli) (built: Nov 27 2020 12:26:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
```

Similarly, there is PHP 7.4.13 only in the rebuilt docker. But I see that my local Ubuntu 18.04 and 20.04 only have that patch release also - so maybe something upstream has not become available yet.

Anyway, the point of this issue is that I think we should "regularly" rebuild the PHP images to have the latest patch releases of PHP.

If we setup drone to automatically run a "monthly" job, then it will happen automatically. But then if the CI publishes the release, but something is broken in it (that the CI did not detect), other CI that uses it will suddenly break, and people will find it difficult to remember "last night was the monthly docker PHP update". They will fluff around looking for why the CI suddenly broke.

But if we run it manually, like I did this morning, then we will forget to do it.

Catch-22.

**Comment by phil-davis** [comment]
Note: I just reran CI manually to get the latest PHP patch releases as at 2021-11-25
https://drone.owncloud.com/owncloud-ci/php/505
That installed PHP 7.4.26 (and the latest of other PHP patch versions)
https://www.php.net/ChangeLog-7.php#7.4.26

**Comment by phil-davis** [comment]
I tried re-running the CI from a few months ago:
https://drone.owncloud.com/owncloud-ci/php/516/25/2

For PHP 8.0 (and 5.6) there are lots of:
```
Warning: foreach() argument must be of type array|object, null given in Command.php on line 249
PHP Warning:  foreach() argument must be of type array|object, null given in /usr/share/php/PEAR/Command.php on line 249
```
and then:
```
XML Extension not found

The command '/bin/sh -c ln -s /usr/include/oracle/12.2/client64 /usr/lib/oracle/12.2/client64/include &&   echo "instantclient,/usr/lib/oracle/12.2/client64/lib" | pecl install oci8-3.0.0' returned a non-zero code: 1

exit status 1
```

I will try to sort that out...

**Comment by xoxys** [comment]
I have added a weekly cron job in Drone for this repo. @phil-davis Something else required for this issue?

**Comment by phil-davis** [comment]
> I have added a weekly cron job in Drone for this repo. @phil-davis Something else required for this issue?

That sounds good - let's see it run and confirm that it does execute all the pipelines for rebuilding the various images. Then we can close.

**Comment by xoxys** [comment]
Then I'll temp change to daily to speed up verification.

**Comment by xoxys** [comment]
Works, and all pipelines were executed. Please reopen if something is missing.

![image](https://user-images.githubusercontent.com/3391958/196374351-1df98cd3-f22c-4ed9-bcda-41e269ca54fb.png)
