### ISSUE TITLE
Images for php7.0-php7.3 are no longer building

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-ci/php#165]
Looks like some old-version PHP has "gone away" in conjunction with whatever Ubuntu we are trying to install it on...

We should be able to just remove all that. We do not need PHP 7.3 or earlier in any CI any more.

And I think that if we remove the old PHP build pipelines, the existing docker images for those versions will remain being published as-they-are. Is that correct @xoxys ?

_Originally posted by @phil-davis in https://github.com/owncloud-ci/php/issues/164#issuecomment-1723729343_

**Comment by xoxys** [comment]
> And I think that if we remove the old PHP build pipelines, the existing docker images for those versions will remain being published as-they-are. Is that correct @xoxys ?

That is correct.
