### ISSUE TITLE
PHP7.2 and memcached causing segmentation fault

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-ci/php#33]
We've seen in some PRs in owncloud/core that php7.2 + memcached can cause segmentation faults.

For now in #32 memcached has been removed.

While debugging @crrodriguez has shared, that this issue happens when php shuts down and unloads the module - this might be circumvented by setting

`export ZEND_DONT_UNLOAD_MODULES=1`

**Comment by crrodriguez** [comment]
Correct. We could also try to build php with enable debug and debug extensions and try to reproduce again and fix it.

**Comment by phil-davis** [comment]
The linked PRs above addressed this. And PHP  7.2 is soon EOL anyway - closing.
