### ISSUE TITLE
Use node 8 LTS

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-ci/php#37]
Some time ago, we (oc engineers) agreed that our apps/core should be built with Node8 LTS 

currently we use node6 

Ref: https://github.com/owncloud-ci/php/blob/master/Dockerfile#L14

**Comment by tboerger** [comment]
Just to mention that, @deepdiver1975 requested the current version as a minimum to get yarn working.

**Comment by DeepDiver1975** [comment]
I'm fine to move on an use node 8
