### ISSUE TITLE
add php7.3 image

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-ci/php#79]
PHP7.3 is in RC phase - it would be great to add it as soon as possible to be out with ownCloud 11

First try is in branch [7.3](https://github.com/owncloud-ci/php/tree/7.3) - however the following extensions still triggers installation of `7.2` base packages

- php-redis 
- php-memcached 
- php-imagick  -  https://github.com/oerdnj/deb.sury.org/issues/940
- php-smbclient 
- php-apcu 

Thus they have been removed for the time being

**Comment by patrickjahns** [comment]
@DeepDiver1975 - you worked on this - please document what there is still todo

**Comment by DeepDiver1975** [comment]
- oracle module  is currently no compiling with php7.3 see https://bugs.php.net/bug.php?id=76903

further findings need to be documented as we progress - https://github.com/owncloud/core/pull/32821
currently we are stuck where the sabre libs are not ready for 7.3 - working on that ....
