### ISSUE TITLE
Newer imagick policy on ubuntu needs adaption ... 

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-ci/php#83]
![screenshot from 2018-11-02 16-06-09](https://user-images.githubusercontent.com/1005065/47923404-a0a0aa00-deb9-11e8-9848-88657fa9a9d8.png)

Recent Ubuntu disabled ghostscript .. we need to adopt ..

@tboerger simply overwrite this file - or what is the most resonable approach? THX

**Comment by DeepDiver1975** [comment]
file in question  more /etc/ImageMagick-6/policy.xml

**Comment by DeepDiver1975** [comment]
![screenshot from 2018-11-02 16-14-27](https://user-images.githubusercontent.com/1005065/47923695-6be12280-deba-11e8-8a5f-e417cc1ddbf7.png)

**Comment by DeepDiver1975** [comment]
prs to all php version are open .....

**Comment by tboerger** [comment]
Solved for all versions.
