### ISSUE TITLE
Missing extensions in PHP 7.3 container

### ISSUE THREAD

**Issue by phil-davis** [owncloud-ci/php#89]
``phan`` needs the ``ast`` extension
``phpstan`` needs the ``apcu`` extension

See test/trial PHP 7.3 core PR https://github.com/owncloud/core/pull/33987 for the typical errors generated.

**Comment by tboerger** [comment]
When these are missing somebody forgot to copy them from the other versions Dockerfile :)

**Comment by patrickjahns** [comment]
> When these are missing somebody forgot to copy them from the other versions Dockerfile :)

@tboerger 
Not correct, when we started with building the first iteration, theses packages were purposely left out, as they triggered the installation of php7.2 packages - see https://github.com/owncloud-ci/php/issues/79#issue-360675879
